apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "hub.name" . }}
type: Opaque
stringData:
  password: "{{ .Values.hub.password }}"
{{- if .Values.hub.tls_cert -}}
  cert: "{{ .Values.hub.tls_cert }}"
{{- end }}
